const carData = {
    "Acura": ["ILX", "MDX", "NSX", "RDX", "RLX", "TLX"],
    "Alfa Romeo": ["4C", "Giulia", "Stelvio"],
    "Aston Martin": ["DB11", "DBX", "Vantage"],
    "Audi": ["A3", "A4", "A5", "A6", "A7", "A8", "Q3", "Q5", "Q7", "Q8", "R8", "TT"],
    "Bentley": ["Bentayga", "Continental", "Flying Spur"],
    "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4"],
    "Buick": ["Enclave", "Encore", "Encore GX", "Envision"],
    "Cadillac": ["CT4", "CT5", "Escalade", "XT4", "XT5", "XT6"],
    "Chevrolet": ["Blazer", "Bolt EV", "Camaro", "Colorado", "Corvette", "Equinox", "Malibu", "Silverado", "Suburban", "Tahoe", "Traverse", "Trax"],
    "Chrysler": ["300", "Pacifica", "Voyager"],
    "Dodge": ["Challenger", "Charger", "Durango", "Journey"],
    "Ferrari": ["488", "812", "F8", "Portofino", "Roma", "SF90"],
    "Fiat": ["500", "500L", "500X", "Spider"],
    "Ford": ["Bronco", "EcoSport", "Edge", "Escape", "Expedition", "Explorer", "F-150", "Mustang", "Ranger", "Transit"],
    "Genesis": ["G70", "G80", "G90", "GV80"],
    "GMC": ["Acadia", "Canyon", "Sierra", "Terrain", "Yukon"],
    "Honda": ["Accord", "Civic", "CR-V", "HR-V", "Insight", "Odyssey", "Passport", "Pilot", "Ridgeline"],
    "Hyundai": ["Elantra", "Kona", "Palisade", "Santa Fe", "Sonata", "Tucson", "Venue"],
    "Infiniti": ["Q50", "Q60", "QX50", "QX60", "QX80"],
    "Jaguar": ["E-PACE", "F-PACE", "F-TYPE", "I-PACE", "XE", "XF"],
    "Jeep": ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler"],
    "Kia": ["Forte", "K5", "Niro", "Optima", "Rio", "Seltos", "Sorento", "Soul", "Sportage", "Telluride"],
    "Lamborghini": ["Aventador", "Huracan", "Urus"],
    "Land Rover": ["Defender", "Discovery", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
    "Lexus": ["ES", "GX", "IS", "LC", "LS", "LX", "NX", "RC", "RX", "UX"],
    "Lincoln": ["Aviator", "Corsair", "Nautilus", "Navigator"],
    "Maserati": ["Ghibli", "Levante", "Quattroporte"],
    "Mazda": ["CX-3", "CX-30", "CX-5", "CX-9", "Mazda3", "Mazda6", "MX-5 Miata"],
    "McLaren": ["570S", "600LT", "720S", "GT"],
    "Mercedes-Benz": ["A-Class", "C-Class", "CLA", "E-Class", "G-Class", "GLA", "GLC", "GLE", "GLS", "S-Class", "SL", "SLC"],
    "MINI": ["Clubman", "Countryman", "Hardtop"],
    "Mitsubishi": ["Eclipse Cross", "Mirage", "Outlander", "Outlander Sport"],
    "Nissan": ["Altima", "Armada", "Frontier", "Kicks", "Leaf", "Maxima", "Murano", "Pathfinder", "Rogue", "Sentra", "Titan", "Versa"],
    "Porsche": ["718", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
    "Ram": ["1500", "2500", "3500", "ProMaster"],
    "Rolls-Royce": ["Cullinan", "Ghost", "Phantom", "Wraith"],
    "Subaru": ["Ascent", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "WRX"],
    "Tesla": ["Model 3", "Model S", "Model X", "Model Y"],
    "Toyota": ["4Runner", "Avalon", "Camry", "Corolla", "Highlander", "Land Cruiser", "Prius", "RAV4", "Sequoia", "Sienna", "Tacoma", "Tundra", "Venza"],
    "Volkswagen": ["Arteon", "Atlas", "Golf", "Jetta", "Passat", "Tiguan"],
    "Volvo": ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"]
};
